"""link field added

Revision ID: 5b6f111147fb
Revises: 5064d4ccc988
Create Date: 2022-05-25 01:53:19.113364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6f111147fb'
down_revision = '5064d4ccc988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('link', sa.String(length=256), nullable=False))
    op.drop_column('courses', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('courses', 'link')
    # ### end Alembic commands ###
